### ISSUE TITLE
Curve.Offset doesn't behave consistently with the curve's base geometry.

### ISSUE THREAD

**Issue by JacobSmall** [DynamoDS/Dynamo#10852]
## Dynamo version

2.5.2

## Operating system

Windows 10

## What did you do? 

Offset isocurves generated from a planar surface.

## What did you expect to see?

The curves maintaining the original plane of the surface.

## What did you see instead?

One of the curves was offset in the Z axis. This doesn't match the coordinate system of the curve which further illustrates the issue with the inconsistency.
![image](https://user-images.githubusercontent.com/29869395/86633794-1ae2d500-bf9f-11ea-88e1-7aff361fe5e1.png)

**Comment by aparajit-pratap** [comment]
Fixed in Dynamo 2.10.

**Comment by sybold** [comment]
not fixed, depending on the angle of the curve, the result is different.


> Fixed in Dynamo 2.10.

are you sure? https://forum.dynamobim.com/t/offset-pline-fails-on-some-lines/57298/5
using core 2.4.1.6394 and civil3d 2.4.1.2161

**Comment by aparajit-pratap** [comment]
@sybold the fix will be available in release 2.10, which you probably don't have yet.
