### ISSUE TITLE
Crash report from Dynamo 2.6.1.8786

### ISSUE THREAD

**Issue by JohanWannes** [DynamoDS/Dynamo#11603]
# Issue Description
The node Data.ImportExcel and Data.ExportExcel don't work anymore.

### What did you do?
Start a script.

### What did you expect to see?
The import of data from Excel into the Revit model.

### What did you see instead?
Warning: Data.ImportExcel operation failed.

### What packages or external references (if any) were used?
Archi-lab.net, bimorphNodes, Clockwork for Dynamo 2.x, Data-Shapes, Orchid, Prorubim Core Kit 2.x, Prorubim Revit Kit 2.x, spring nodes, SteamNodes, 

### Stack Trace
```
Run completed with warnings
```

---
OS: `Microsoft Windows NT 10.0.19042.0`
CLR: `4.0.30319.42000`
Dynamo: `2.6.1.8786`

**Comment by JohanWannes** [comment]
Dynamo Version: Dynamo Core 2.6.1.8786; Dynamo Revit 2.6.1.8850
Operating System: Windows 10 pro
It works on the workstation of my colleague.
I also pasted the notifications I get when opening dynamo.
![image](https://user-images.githubusercontent.com/62556048/114382315-87bd7800-9b8c-11eb-8f86-e4f58fadb6af.png)
![image](https://user-images.githubusercontent.com/62556048/114382628-de2ab680-9b8c-11eb-8208-70c75c10aea3.png)

**Comment by JohanWannes** [comment]
The problems occur on the nodes Data.ImportExcel and Data.ExportExcel.

**Comment by QilongTang** [comment]
hi @JohanWannes , would you help me out on two things:
- if you hover over the yellow bubble above node Data.ImportExcel, what warning do you see when it expands?
- Check if your installed excel locally and if your local excel version is same with your college where the same graph works

These two pieces of details will greatly help our team digest what is going on. We will determine the next step then.

**Comment by JohanWannes** [comment]
Hello Aaron,

Thank you very much for your help!
I got the answer to my problems… I found out that I was running an Office 32 bit version.
I updated to the 64 bit version and the problem is solved 😊 !

The nodes Data.ImportExcel and Data.ExportExcel do’nt give those ‘yellow bubbles’ anymore.
(The message in the yellow bubbles was: “Data.ImportExcel operation failed” and “Data.ExportExcel operation failed”.)

Thanks again for your quick responses and I hope I didn’t give you guys too much trouble!



Met vriendelijke groeten, Johan Leenaerts
Rechtstreeks nr. +32 3 317 08 94
***@***.***D73045.7CDB4320]<http://www.heuvel-folie-serres.com/>
***@***.***D73045.7CDB4320]<http://www.veestal.be/>
Heuvel-Folie-Serres bv – Tel.: +32 3 313 89 76 -- Groot Veerle 8 – 2960 Sint Lenaarts – België – [e943ecc8-5be2-4768-a17e-1b829b908afe] <https://www.facebook.com/Heuvel-Folie-Serres-1503659263298239/>


Van: Aaron (Qilong) ***@***.***>
Verzonden: dinsdag 13 april 2021 5:50
Aan: DynamoDS/Dynamo ***@***.***>
CC: Johan Leenaerts ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DynamoDS/Dynamo] Crash report from Dynamo 2.6.1.8786 (#11603)


hi @JohanWannes<https://github.com/JohanWannes> , would you help me out on two things:

  *   if you hover over the yellow bubble above node Data.ImportExcel, what warning do you see when it expands?
  *   Check if your installed excel locally and if your local excel version is same with your college where the same graph works

These two pieces of details will greatly help our team digest what is going on. We will determine the next step then.

**Comment by QilongTang** [comment]
@JohanWannes Thank you. I don't think I have seen this case before but it's worth adding in our own notes. I will pass your case to our support so they can help more other customers. Closing and glad you were able to resolve yourself :)

**Comment by Nickeyzhong** [comment]
i have same issue that is occurred in Revit dynamo, (the excel is version 64bit)
but the issue is still occurred "Warning: Data.ExportExcel operation failed."
![image](https://user-images.githubusercontent.com/19465993/182286636-9a165dec-e789-406c-8231-daf89928b174.png)
