### ISSUE TITLE
Data-Shapes package info stamp crash

### ISSUE THREAD

**Issue by HVCFOG3Y34** [DynamoDS/Dynamo#12260]
# Issue Description
I try to use the package info stamp function in Data-Shapes 2022.2.97 and it crashes - both the copy to clipboard and create text note.

## Dynamo version
Dynamo: `2.12.0.5650`

## Operating system
OS: `Microsoft Windows NT 10.0.19043.0`

## What did you do?
Use package info stamp functionality in Data-Shapes 2022.2.97. 

## What did you expect to see?
Package info stamp text note.

## What did you see instead?
A crash.

### Loaded Packages
- archi-lab.net 2022.212.2722
- BIM4Struc.Productivity 2.2.2
- bimorphNodes 4.0.13
- BumbleBee 2021.25.3
- Clockwork for Dynamo 2.x 2.3.0
- Data-Shapes 2022.2.97
- DynaMonito 2.1.1
- HDI 1.2022.0
- Monocle 2021.10.1
- Orchid 212.1.0.7978
- Quasar 2.1.3
- Rhythm 2021.7.3
- Slingshot! for Dynamo 2014.11.30
- spring nodes 204.1.0

## Stack Trace
```
Could not find a part of the path 'C:\Users\<user>\Downloads\%BuiltInPackages%'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at DataShapes.ScriptInfoStamp.InfoStamp(List`1 pdirs)
   at DataShapes.ScriptInfoStamp..ctor(ReadyParams p, DynamoViewModel vm, List`1 pdirs, Boolean Note)
   at DataShapes.DataShapesVE.<>c__DisplayClass11_1.<Loaded>b__11(Object s, RoutedEventArgs a)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

---
CLR: `4.0.30319.42000`

**Comment by HVCFOG3Y34** [comment]
> hey @HVCFOG3Y34 thanks for sharing this! I'll look into it.

FYI, the crash still happens even if Data-Shapes is the only package installed.

**Comment by MostafaElAyoubi** [comment]
I think you have the path "C:\Users\<user>\Downloads\%BuiltInPackages" in your package and node paths. Could check if it is the case please? If so , can you remove it and try again ?

**Comment by mjkkirschner** [comment]
@HVCFOG3Y34 -

1. is that the actual path? The %builtin-packages% path should be inside the same folder containing your dynamo binaries.

2. Are you using sandbox or revit?


@MostafaElAyoubi - it's unclear if the path above is the actual path or not, but in any case, the *normal* %builtin-packages% path can't easily be removed - instead when trying to access a path make sure to wrap in a try/catch and check for io exceptions or check the permissions of the directory before trying to access.

**Comment by HVCFOG3Y34** [comment]
@MostafaElAyoubi @mjkkirschner

1. The actual path for "C:\Users\<user>\Downloads\%BuiltInPackages%" has "<user> replaced with my user name. I just removed it for privacy reasons. But that path is not in my package and node paths. The only path I added was a folder under my main C drive "C:\Dynamo Server Packages 2022" which all my packages are loaded from.
2. I am using Dynamo for Revit.

**Comment by HVCFOG3Y34** [comment]
I tried running the package info stamp again jus to see what would happen, and I got a different path this time. Again, this path is not in my node and package paths. 

```
Could not find a part of the path 'C:\Program Files\Autodesk\Revit 2022\%BuiltInPackages%'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path, String searchPattern, SearchOption searchOption)
   at DataShapes.ScriptInfoStamp.InfoStamp(List`1 pdirs)
   at DataShapes.ScriptInfoStamp..ctor(ReadyParams p, DynamoViewModel vm, List`1 pdirs, Boolean Note)
   at DataShapes.DataShapesVE.<>c__DisplayClass11_1.<Loaded>b__12(Object s, RoutedEventArgs a)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by MostafaElAyoubi** [comment]
Thanks for the prompt reply. 
As @mjkkirschner said I need to implement a try catch on the part of the code. Will do it tomorrow and publish a new version of the package. I'll update this thread.

**Comment by MostafaElAyoubi** [comment]
Version 2022.2.98 should fix the issue. Can you please confirm?

**Comment by HVCFOG3Y34** [comment]
@MostafaElAyoubi 

Didn't fix it. It now crashes as soon as I hit the package info stamp button.

```
Object reference not set to an instance of an object.

   at DataShapes.DataShapesVE.<>c__DisplayClass11_0.<Loaded>b__10()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by HVCFOG3Y34** [comment]
@MostafaElAyoubi 

I can't reproduce the issue, so maybe it was just a fluke? Either way, it works now. Thank!!

**Comment by MostafaElAyoubi** [comment]
Excellent :) . Well if it comes up again met me know. Cheers!

**Comment by HVCFOG3Y34** [comment]
I'm having issues with the package info stamp again. Its not a crash this time though, Its not including some packages sometimes.

![image](https://user-images.githubusercontent.com/6226581/141310004-870fdc04-17c0-40da-bf41-84b21d6b38f4.png)

**Comment by MostafaElAyoubi** [comment]
Okay I think this calls for an unpdate using the dependency information contained in the dyn :) 
The method used so far xas created before that information was available and isn't perfect. I'll push another update and let you know

**Comment by MostafaElAyoubi** [comment]
It should perform better now (v.2022.2.99)

**Comment by HVCFOG3Y34** [comment]
@MostafaElAyoubi 
Apologies for the late reply. Its not missing the packages anymore, but the time stamp at the bottom is gone.

**Comment by MostafaElAyoubi** [comment]
right !! 😄 Thanks for trying it out so fast. Just pushed an update.

**Comment by HVCFOG3Y34** [comment]
@MostafaElAyoubi 
All good now. Thanks for the quick updates!!
