### ISSUE TITLE
Crash report from Dynamo 2.12.1.8246

### ISSUE THREAD

**Issue by KeesdBruin** [DynamoDS/Dynamo#13906]
# Issue Description
Please fill in the following information to help us reproduce the issue:

## Dynamo version
Dynamo: `2.12.1.8246`

## Operating system
OS: `Microsoft Windows NT 10.0.19044.0`

## What did you do?
(Fill in here)
In Revit 2022: Export a Dynamo graph to png.
This is not working for a lot of scripts. Every time the same error / crash
I tried also in Revit 2023 with same result (also crashing Dynamo)
I also tried different PC's; same problems.

Please fix this bug! It is very inconvenient not to be able to make png-exports of scripts for evaluation purpose
I Guess this problem will also be there in Dynamo 2.17?

## What did you expect to see?
(Fill in here)

## What did you see instead?
(Fill in here)

### Loaded Packages
- archi-lab.net 2022.212.2922
- bimorphNodes 4.1.1
- Clockwork for Dynamo 2.x 2.3.0
- Data-Shapes 2022.2.100
- Genius Loci 2022.1.5
- Miscellany 1.2.0
- Modelical 2022.3.2
- Orchid 260.0.3.7626
- Rhythm 2022.3.2
- SHG_RevitNodes 2022.1.2
- GenerativeDesign 1.10.10.0
- GenerativeDesign.Extension 1.10.10.0
- GenerativeDesign.Revit 1.10.10.0

## Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```
The image data generated an overflow during processing.

   at System.Windows.Media.Renderer.Render(IntPtr pRenderTarget, Channel channel, Visual visual, Int32 width, Int32 height, Double dpiX, Double dpiY, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual, Matrix worldTransform, Rect windowClip)
   at System.Windows.Media.Imaging.BitmapVisualManager.Render(Visual visual)
   at Dynamo.Views.WorkspaceView.SaveWorkspaceAsImage(String path)
   at Dynamo.ViewModels.DynamoViewModel.OnRequestSaveImage(Object sender, ImageSaveEventArgs e)
   at Dynamo.ViewModels.DynamoViewModel.SaveImage(Object parameters)
   at Dynamo.ViewModels.DynamoViewModel.ShowSaveImageDialogAndSaveResult(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---
CLR: `4.0.30319.42000`

**Comment by QilongTang** [comment]
hi @KeesdBruin Thanks for reporting, this bug should have been fixed as part of Dynamo 2.17

**Comment by KeesdBruin** [comment]
Hi Aaron,

I have tested the scripts and issue also in Revit 2024 (Dynamo 2.17) with the same errors as result.
So to me it seems that this issue is still not solved!

Kind regards,

Kees de Bruin

BIM specialist
T  +31 (0) 302417615
***@***.******@***.***>


***@***.***

Interbuild Management B.V.

Postadres
P.O. Box 9090
3506 GB Utrecht

Bezoekadres
Otto Hahnweg 20
3542 AX Utrecht
The Netherlands

KvK-nummer
30207612

www.stamhuis.nl<http://www.stamhuis.nl/>

Van: Aaron (Qilong) ***@***.***>
Verzonden: vrijdag 19 mei 2023 15:44
Aan: DynamoDS/Dynamo ***@***.***>
CC: Kees de Bruin | Stamhuis ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DynamoDS/Dynamo] Crash report from Dynamo 2.12.1.8246 (Issue #13906)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

hi @KeesdBruin<https://github.com/KeesdBruin> Thanks for reporting, this bug should have been fixed as part of Dynamo 2.17

**Comment by QilongTang** [comment]
Oh that is good to know @KeesdBruin , I suspect it is related to particular graph, do you think you can share the script with me and my team at Autodesk directly?

**Comment by KeesdBruin** [comment]
Hi Aaron,

Issue was there in several related scripts. To check what’s going on, I tested in Revit 2021 / 2022 / 2023 / 2024. Also on different hardware (laptops).

By coincidence I solved the problem myself. I was triggered by the warning “image data generated an overflow during processing”.
Problem was that a Dynamo node was situated far beyond the actual extents of the graph. (no idea how it came there)

You can simulate this issue by placing 2 nodes at far distance from each other.

The issue causes a crash of the Dynamo session while trying to write the exported png-file.
I am not able to share that scripts anymore since they are at a further stage of development now.

Kind regards,

Kees de Bruin

BIM specialist
T  +31 (0) 302417615
***@***.******@***.***>


***@***.***

Interbuild Management B.V.

Postadres
P.O. Box 9090
3506 GB Utrecht

Bezoekadres
Otto Hahnweg 20
3542 AX Utrecht
The Netherlands

KvK-nummer
30207612

www.stamhuis.nl<http://www.stamhuis.nl/>

Van: Aaron (Qilong) ***@***.***>
Verzonden: maandag 22 mei 2023 16:55
Aan: DynamoDS/Dynamo ***@***.***>
CC: Kees de Bruin | Stamhuis ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [DynamoDS/Dynamo] Crash report from Dynamo 2.12.1.8246 (Issue #13906)


Oh that is good to know @KeesdBruin<https://github.com/KeesdBruin> , I suspect it is related to particular graph, do you think you can share the script with me and my team at Autodesk directly?

**Comment by mjkkirschner** [comment]
We could export multiple images if this occurs, or drop the overall resolution to a valid resolution.
