### ISSUE TITLE
All Elements Of Category fails for views

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/Dynamo#2970]
Using ```All Elements Of Category``` on the Views category will results in the following warning: 
```Warning: ElementQueries.OfCategory operation failed. 
View cannot be a template view.```
The same happens when using ```All Elements Of Type```

**Comment by jbenoit44** [comment]
any update here? still there in RC2 0.7.5.

**Comment by billingsgr** [comment]
I have Dynamo 0.8.0.950 and this is still an issue? How do we deal with this View Template Error?

**Comment by jbenoit44** [comment]
Still an issue in 0.8.2.1601.
![image](https://cloud.githubusercontent.com/assets/4572196/8276609/d57b28ba-18b8-11e5-823b-2a71a31830a9.png)

**Comment by ksobon** [comment]
Mhmmm, can we get this solved? It would be nice. Thanks!

**Comment by ikeough** [comment]
Duplicated by #2313

**Comment by ParametricMonkey** [comment]
@ikeough  Still an issue in 1.0.1 on Revit 2016 r2. Can we get this solved. It looks like its been around for a while now.

![dynmo_views](https://cloud.githubusercontent.com/assets/10913639/16180839/e687ea96-36d3-11e6-923f-a36c5559e9f6.jpg)

**Comment by ParametricMonkey** [comment]
@ikeough @kronz Can someone have a look at this please

**Comment by kronz** [comment]
We'll get his for 1.2.  Sorry, this one fell between the cracks.

**Comment by QilongTang** [comment]
A fix attempt is made, see Pull request as reference: https://github.com/DynamoDS/DynamoRevit/pull/1239

**Comment by sm6srw** [comment]
Fixed in 1.2.

**Comment by ikeough** [comment]
:+1:

**Comment by ParametricMonkey** [comment]
@kronz @ikeough I'm running Dynamo v1.2.1.3083 and I am still getting this problem. I thought this had been fixed? It works sometimes but not others and i can't work out why

**Comment by ParametricMonkey** [comment]
The warning is slightly different thought; "Warning: ElementQueries.OfCategory operation failed. 
The managed object is not valid."
