### ISSUE TITLE
sliders are gone! daily build 20150203

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/Dynamo#3675]
![slider](https://cloud.githubusercontent.com/assets/6928491/6026374/9cc1e810-abda-11e4-9ef2-e3caf05c49fc.png)

**Comment by jnealb** [comment]
@epeter- I am unable to reproduce with 0.7.6.3982 (20150203) - if I type 'slider' at the lib search I can create number sliders that work. Were you perhaps expecting 'double sliders'? They are replaced with 'number sliders' in 7.6. If this does not answer your question, can you please provide us with more details?

**Comment by epeter-** [comment]
Am 03.02.2015 um 18:21 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> I am unable to reproduce with 
> 0.7.6.3982 (20150203) - if I type 'slider' at the lib search I can 
> create number sliders that work. Were you perhaps expecting 'double 
> sliders'? They are replaced with 'number sliders' in 7.6. If this does 
> not answer your question, can you please provide us with more details?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3675#issuecomment-72693265>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com

**Comment by epeter-** [comment]
![slider](https://cloud.githubusercontent.com/assets/6928491/6026383/ac7ed1aa-abda-11e4-8978-7670927310f2.png)

**Comment by RodRecker** [comment]
got it - so the actual slider control is missing.

**Comment by jnealb** [comment]
@RodRecker @epeter- Very odd - I get fully decorated sliders. Investigating.

**Comment by jnealb** [comment]
@RodRecker @epeter- Installing 20150203 on a newly created VM does not reproduce the issue, and when I installed on my machine I manually un-installed the previous version of 7.6 and cleared out the 'Dynamo 0.7' folder under \Program Files. This may be an update issue, can you re-install after manually un-installing and clearing the folder?

**Comment by pboyer** [comment]
@epeter- , Do you have CoreNodeModelsWpf.dll in your nodes folder?  This would cause this issue.  Are their UI issues with Number or Boolean?

@jnealb, We should confirm that this dll is not missing on upgrade from 0.7.5 -> 0.7.6.

**Comment by jnealb** [comment]
@epeter- @pboyer @RodRecker @ikeough @ramramps Tracked with MAGN-6203

**Comment by jnealb** [comment]
@pboyer CoreNodeModelsWpf.dll  is missing from the nodes folder on upgrade from 0.7.5 -> 0.7.6

**Comment by ikeough** [comment]
This is not an issue with a missing CoreNodeModelsWpf. It's an issue with a duplicate DSCoreNodes.dll, and it is fixed in [this commit](https://github.com/DynamoDS/Dynamo/commit/c01e043895da04476a09b42d61a2d99024f848bf)

**Comment by jnealb** [comment]
@epeter- Can you please try installing with the latest build 0.7.6.20150204T0658? We think this is fixed.

**Comment by epeter-** [comment]
@jnealb sliders are back, select model element(s) still not functional

**Comment by jnealb** [comment]
@epeter- Thanks! Then let's close this issue and move the select model elements question to a new one, if that is ok with you?

**Comment by epeter-** [comment]
absolutely

Am 06.02.2015 um 15:29 schrieb Neal Burnham:
>
> @epeter- <https://github.com/epeter-> Thanks! Then let's close this 
> issue and move the select model elements question to a new one, if 
> that is ok with you?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DynamoDS/Dynamo/issues/3675#issuecomment-73244070>.
>



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
http://www.avast.com
