### ISSUE TITLE
Crash when starting 0.8.1.20150416T2058 in sandbox and Revit addin modes

### ISSUE THREAD

**Issue by ralvarez76** [DynamoDS/Dynamo#4264]
Here is the Revit error:

Object reference not set to an instance of an object.

   at Dynamo.UI.Views.LibrarySearchView.OnTopResultTargetUpdated(Object sender, DataTransferEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Data.BindingExpression.OnTargetUpdated(DependencyObject d, DependencyProperty dp)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

Here is the Sandbox error:

Error registering effect: Object reference not set to an instance of an object.

DPFCanvas: Error attaching element: The given key was not present in the dictionary.

Here is my system's spec:

Intel I&-4790k @ 4ghz
NVIDIA Quadro K2200 - Driver Version 340.52

**Comment by monikaprabhu** [comment]
@ralvarez76 this build starts ok at my end.Anybody else seeing this error ?

**Comment by ikeough** [comment]
Hey @ralvarez76. This is a bug with the new visualization stuff. I'm guessing you got a dialogue that said that you were missing a dll. I believe this was already reported [here](https://github.com/DynamoDS/Dynamo/issues/4211). If it's something different, let me know.

**Comment by MartinHenriksen** [comment]
@ralvarez76 have you tried renaming the .dll to "sharpdx_direct3d11_1_effects_x64.dll" as in the issue  @ikeough has linked above? If that is a usable workaround for you it might confirm that it is indeed the same issue. The issue persists on my end but renaming works for me.

**Comment by ralvarez76** [comment]
Yes renaming fixes the problem. Although I actually made a copy of the dll and left both in there. 

Regards,

Rafael Alvarez

**Comment by ralvarez76** [comment]
I spoke too soon. This fixes the problem of crashing when launching the application, but one it runs I cant get any 3d canvas previews. Zoom to fit shows nothing,

**Comment by jnealb** [comment]
@ralvarez76 This is being tracked with MAGN-7125

**Comment by ralvarez76** [comment]
Thanks jnealb. I noticed that when I run Dynamo on home with a Geforce card I don't have this problem with 0.8.1. I will try to update my display drivers to see if it helps with the issue.

**Comment by ikeough** [comment]
I believe this bug has to do with the version of DirectX that the version of SharpDX used by Helix3D uses. This is described [here](https://github.com/sharpdx/SharpDX/issues/327).

**Comment by ikeough** [comment]
@ralvarez76 We believe this issue is resolved with https://github.com/DynamoDS/Dynamo/pull/4498. Please confirm that the latest daily build is working for you and we will close.

**Comment by ralvarez76** [comment]
I am still getting the same errors. Deleting "sharpdx_direct3d11_1_effects_x64.dll" and renaming "sharpdx_direct3d11_effects_x64.dll" to "sharpdx_direct3d11_1_effects_x64.dll" fixes it.

![error 1](https://cloud.githubusercontent.com/assets/2349069/7736519/2dd6eab4-fef9-11e4-8dd8-5a2f0f474384.PNG)
![error 2](https://cloud.githubusercontent.com/assets/2349069/7736527/33b23ab0-fef9-11e4-8f24-1ede158f509c.PNG)

**Comment by RodRecker** [comment]
We don't yet have a build with #4498. We should have one by tomorrow if not sooner.

**Comment by ikeough** [comment]
@ralvarez76 Try the daily build from today. You shouldn't have to rename anything now and the D3DCompiler_xx missing error should be resolved. Fingers crossed :)

**Comment by ralvarez76** [comment]
Ok, I installed the latest daily build (DynamoInstall0.8.1.20150521T0846.exe) and I still get the "DynamoSandbox has stopped working" crash. However if I start it a second time it launches fine and works.

I am getting this same crash on my system at home that uses an Nvidia GeForce card (Win 7 64 Bit), which was not having any crashes before. Regardless it looks like its just a first launch crash, after that it works fine.

Maybe there is some sort of test of the graphics driver / card that is launched that is failing?

**Comment by jnealb** [comment]
@ralvarez76 @ikeough We are investigating a similar instance of "first time in" here in-house.

**Comment by ikeough** [comment]
@ralvarez76 Thanks for checking. Is there anything useful in the Dynamo log after the first crash? Does the it crash the first time only after installation or every time Dynamo starts after you boot up?

That's really interesting. @jnealb The crash on the box we tested today was because we had mucked with the names of the DirectX dlls for testing. So, it's a different issue.

**Comment by ralvarez76** [comment]
The crash only happens after first launch after installation. Does not happen after that, even if I reboot the computer. Here is the content of the log file:

Dynamo log started 5/22/2015 11:30:19 AM
5/22/2015 11:30:20 AM : RequestUpdateVersionInfo
5/22/2015 11:30:20 AM : Requesting version update info...
5/22/2015 11:30:20 AM : Dynamo -- Build 0.8.1.1404
5/22/2015 11:30:20 AM : Dynamo will use the package manager server at : https://www.dynamopackages.com
5/22/2015 11:30:20 AM : Dynamo is up to date.
5/22/2015 11:30:20 AM : Duplicate migration type registered for SunPathDirection
5/22/2015 11:30:22 AM : Build error for library: C:\Users\ralvarez\AppData\Roaming\Dynamo\0.8\packages\Grapher\bin\svg.dll
5/22/2015 11:30:22 AM : Can't import System.Collections.Generic.Dictionary`2+ValueCollection[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], ValueCollection is already imported as System.Collections.Generic.Dictionary`2+KeyCollection[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], namespace support needed.
5/22/2015 11:30:22 AM : Exception when attempting to load package StockRoom for Dynamo from C:\Users\ralvarez\AppData\Roaming\Dynamo\0.8\packages\Stockroom
5/22/2015 11:30:22 AM : System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
5/22/2015 11:30:22 AM : Backup files timer is started with an interval of 60000 milliseconds
5/22/2015 11:30:24 AM : Welcome to Dynamo!
5/22/2015 11:30:24 AM : 00:00:01.2813248 elapsed for loading Dynamo main window.
5/22/2015 11:30:24 AM : RENDER : Rendering Tier: 2
5/22/2015 11:30:24 AM : RENDER : Pixel Shader 3 Supported: True
5/22/2015 11:30:24 AM : RENDER : Pixel Shader 4 Supported: False
5/22/2015 11:30:24 AM : RENDER : Software Effect Rendering Supported: True
5/22/2015 11:30:24 AM : RENDER : Maximum hardware texture size: 16384,16384

**Comment by jnealb** [comment]
@ralvarez76 @ikeough We think this may be resolved with the latest 8.2 build. Can you please check? Thanks.

**Comment by ralvarez76** [comment]
I am not getting any more errors at first launch with the latest build 0.8.2.20150527T0853. Yes!
