### ISSUE TITLE
Problem in recent builds for Windows 8.1 and 10

### ISSUE THREAD

**Issue by Kelcyo** [DynamoDS/Dynamo#5033]
I'm using Dynamo latest build (DynamoInstall0.8.2.20150731T0444) on equipment SONY VAIO VGN with the following Windows 7, 8.1 and 10. But only on Windows 7 with last build visualization and execution on the desktop work correctly. In Windows 8.1 and 10, I observed that the poblema came into being starting the build (DynamoInstall0.8.1.20150409T1246).
What may be happening in these builds for Windows 8.1 and 10?

**Comment by monikaprabhu** [comment]
@Randy-Ma - please take a look at this -

**Comment by RodRecker** [comment]
@Kelcyo Please give us more details on the problem that you are seeing.

**Comment by Kelcyo** [comment]
The problem has been mentioned in the build improvements, but following the steps described was not solved.
•	Known issues for graphics hardware https://github.com/DynamoDS/Dynamo/wiki/Known-Issues
“If you have added DynamoSandbox.exe to the NVidia control panel's list of applications, when re-installing or updating Dynamo you may see a blank 3D view or missing menus. Remove the DynamoSandbox.exe entry from the list of applications in the NVidia control panel to solve this issue. You may have to re-add this program entry in the NVidia Control Panel to override specific graphics features for Dynamo. If your NVidia graphics adapter supports it, we recommend the "High Performance Processor" mode.”
My graphics card is an Nvidia Geforce 9600M GT and graphics drivers are updated to the windows used. Still, it's not shown the work area properly. When running the script is shown correctly in Revit.

 
![dynamo_erro](https://cloud.githubusercontent.com/assets/11540152/9045557/6e4dc3f6-39fa-11e5-8d0c-9828b2fa0e7d.png)

**Comment by jnealb** [comment]
@Kelcyo Can you please run DxDiag on Win8.1 and 10 and send us its output as a file? Thanks, Neal.Burnham@autodesk.com

**Comment by Kelcyo** [comment]
I have already sent diagnostic files for windows 7, 8.1 and 10 still awaiting a solution. The previous version 8.1 Dynamo does not meet the requisites for me not contain new nodes updated.

**Comment by jnealb** [comment]
@Kelcyo Yes thank you - we are working towards a solution and will update you asap.

**Comment by ikeough** [comment]
Relates to #5054.

**Comment by Kelcyo** [comment]
These guidelines do not solve the problem.
First Windows 10 does not do the downgrade, saying that already have the latest version installed (DirectX 11.1).
According to believe than DirectX problem as the Build (0.8.1.20150406T1239) when installed works perfectly in these OS. The most likely is the question of compilation.

**Comment by Kelcyo** [comment]
Lords some temporary solution to this problem, or only when you exit the final build.

**Comment by Kelcyo** [comment]
Lords some temporary solution to this problem, or only when you exit the final build

**Comment by Kelcyo** [comment]
We're a month without solving this bug. The reporting me, any progress or users with graphics cards in notebook old were unable to use the tool with latest builds?

**Comment by tcacciuto** [comment]
I have the same display issue Win 7, display card AMD FirePro and Intel on HP ZBook. I can see 3D preview only on Dynamo 8.0. No newer release works.

**Comment by jnealb** [comment]
@tcacciuto We are actively working on this; thanks for your patience.

**Comment by jnealb** [comment]
@Kelcyo @tcacciuto Can you please try this again with the latest daily build (10/1) as soon as our server (Dynamobim.org) is back up?

**Comment by RodRecker** [comment]
@Kelcyo @tcacciuto You can get the build now from http://dynamobuilds.com/

**Comment by Kelcyo** [comment]
@RodRecker @jnealb 
#5054 
Gentlemen, 
fortunately the problem was resolved in this build (DynamoInstall0.9.0.20151001T1254).
Thanks for the commitment to solve this problem.

**Comment by RodRecker** [comment]
@Kelcyo Excellent - thank you for testing for us!

**Comment by tcacciuto** [comment]
@RodRecker, @jnealb, 
sorry for my answer in late. I installed the last build 2015-10-14T14:29:41.000Z  and the result is still the same. I have no 3D preview in Dynamo. Win 7 64-bit, Revit 2015.
Let me know if you need any other details.

thank you

**Comment by jnealb** [comment]
@tcacciuto Please, yes: what is your graphics card? Are you running Dynamo as an Addin or standalone?

**Comment by tcacciuto** [comment]
@jnealb 
I run Dynamo as Addin and standalone, the result is the same in both cases.
Here you are the screen shoot showing my graphics cards:
![2015-10-15_0800](https://cloud.githubusercontent.com/assets/14175079/10505955/e596d050-7312-11e5-8ee1-41edb712554a.png)

here you can see AMD catalyst screen showing that dynamo is set to use high performance settings:
![2015-10-15_0803](https://cloud.githubusercontent.com/assets/14175079/10505999/4e1f066a-7313-11e5-865e-54b70c3a0982.png)

Thank you

**Comment by mjkkirschner** [comment]
when you change dynamo sandbox to high performance mode, make sure to select .9 version instead of .8 in the .9 folder..

**Comment by tcacciuto** [comment]
to be sure I Select the right one I uninstalled .8

**Comment by jnealb** [comment]
@tcacciuto Thank you, we are investigating.

**Comment by tcacciuto** [comment]
Guys, do you have any update about graphic issue?

**Comment by RodRecker** [comment]
@tcacciuto - can you try it with the 0.9.0 RC build?
http://dyn-builds-data.s3-us-west-2.amazonaws.com/DynamoReleaseCandidateInstall0.9.0.exe

**Comment by tcacciuto** [comment]
@RodRecker still the same... :(
I'm avaiable for a meeting with screen sharing if this can help you guys.

Thank you

**Comment by RodRecker** [comment]
@jnealb Neal - can you connect with @tcacciuto and try to understand this better?

**Comment by jnealb** [comment]
@tcacciuto Can we chat via email before we go to screen sharing: Neal.burnham@autodesk.com?
