### ISSUE TITLE
Large files with Revit nodes Not loading on v0.9.0

### ISSUE THREAD

**Issue by rsingaby** [DynamoDS/Dynamo#5706]
Large files (1 MB and over) failing to load on version 0.9.0 (on both the official and candidate releases). definition loads (file opens) 1 out of 5 times. When successful, running the definition does NOT generate any of the geometry, and all nodes in the script read “null”. I've been working on this definition for the past 4 months. Up till version 0.8.2 everrything was smooth. Version 0.9 looks amazing, and feels faster, but it's failing to run my large file.

**Comment by jnealb** [comment]
@rsingaby Are you able to send us your large file so that we can debug it?

**Comment by rsingaby** [comment]
Neal, thanks for your reply. Yes, I'm able to send the model, but we'll do this through the official channels. This is a company project and may be confidential to share. We will send it through our autodesk support account, and I'll have your name and email on the support ticket. Does this work? Kindly advise.

**Comment by jnealb** [comment]
@rsingaby That works; neal.burnham@autodesk.com

**Comment by rsingaby** [comment]
Great! Thanks

**Comment by jnealb** [comment]
@rsingaby Are you running Dynamo as a Revit Addin? If so, under View, Background 3d Preview, Available Previews can you please turn off the "Revit Background Preview" and see if this cures the issue?

**Comment by rsingaby** [comment]
@jnealb I tried doing this, as well as turn off 3d preview in the dynamo window, disable detailed usability data reporting , with no result.

we've submitted the models to autodesk support through our company account. Not sure if you've gotten your hands on it yet?

**Comment by jnealb** [comment]
I have but the Revit model gives errors when it loads, pointing to missing components. May I forward you an email with the details?

**Comment by jnealb** [comment]
@rsingaby We are able to reproduce this and are tracking it as MAGN-9093.

**Comment by jnealb** [comment]
@rsingaby We think this is fixed in the latest daily: DynamoInstall0.9.1.20151203T2309. Can you please check? The dyn should load in approximately 2-3 mns and function properly thereafter.

**Comment by rsingaby** [comment]
@jnealb The file successfully loaded, with no freeze, in a fairly short time. I'm still unable to run the geometry. After clicking run, it takes around 20 seconds (usualy needs close to 5 minutes) for run to complete - with every single node reading "null" and no geometry generated in dynamo.
![capture](https://cloud.githubusercontent.com/assets/14059629/11660064/e22449e0-9d90-11e5-9cf9-287536fdd30a.PNG)

**Comment by jnealb** [comment]
@rsingaby Thank you - we are tracking the "all null" issue with MAGN-9142.

**Comment by jnealb** [comment]
@rsingaby We think this is fixed, can you please try with the daily build "post 12/21"?

**Comment by rsingaby** [comment]
Neal, looks like all is in good working condition. Thanks for all your help. Happy Holidays!
