### ISSUE TITLE
PolyCurve.Offset not working

### ISSUE THREAD

**Issue by ParametricMonkey** [DynamoDS/Dynamo#6156]
PolyCurve.Offset not working as intended.

If rectangle fed in, regardless of extendCircular input, fillets are generated, not larger rectangles.

If a series of arcs joined together into a closed polycurve are fed in, an error appears:

"Warning: PolyCurve.Offset operation failed. Unable to compute edge from curve : IG_CURVE_NON_G0 -- Curve is G0 discontinuous"

This means there is no way to accurately offset geometry, particularly when you can't define which side to offset. Offset with point as a reference would be much more useful.

**Comment by ParametricMonkey** [comment]
Looking into this more, 7000 offset is the threshold for the 'extendCircular' to work. Offsetting less than this amount, it is possible to offset a rectangle with square corners. Greater than this amount, it will ALWAYS create the fillets. So it seems this is a units thing.

**Comment by ParametricMonkey** [comment]
also outside of a custom node it will offset in the XY plane. However within a custom node it will offset in the z axis with all inputs the same.

**Comment by aparajit-pratap** [comment]
@ParametricMonkey thanks for your observations. It would be helpful if you shared the graphs you used to reproduce these behaviours so that we could look more closely at the real issues.

**Comment by ParametricMonkey** [comment]
When offsetting a polycurve with a positive offset, one would normally expect it to offset outwards, not inwards.

![error1](https://cloud.githubusercontent.com/assets/10913639/13235783/ede5e7d8-da13-11e5-98d9-9b9358827523.JPG)

With a max offset of -7000 and extend circular set to false it works
![error2](https://cloud.githubusercontent.com/assets/10913639/13235787/f26538fe-da13-11e5-97aa-dc53be403d26.JPG)

Greater than -7000 and the extend circular fails
![error3](https://cloud.githubusercontent.com/assets/10913639/13235789/f4accafa-da13-11e5-8b23-205a9108acfe.JPG)

Save issue of using curve.offset
![error4](https://cloud.githubusercontent.com/assets/10913639/13235790/f8496c18-da13-11e5-9921-ca8a43b3bf78.JPG)

And these in a custom node appear to offset in the z direction, not XY plane.
![error5](https://cloud.githubusercontent.com/assets/10913639/13235867/b2441032-da14-11e5-8f4f-162556148a29.JPG)


Not sure if this is a similar issue to the ASM geometric kernel limitation? https://github.com/DynamoDS/Dynamo/issues/5681#issuecomment-184470675

**Comment by aparajit-pratap** [comment]
No I don't think it is related to 5681. We are tracking this separately. Thanks for the example workflows.

**Comment by aparajit-pratap** [comment]
Tracked in: http://adsk-oss.myjetbrains.com/youtrack/issue/MAGN-9498

**Comment by ParametricMonkey** [comment]
has this been fixed in version 1.0.0?

**Comment by aparajit-pratap** [comment]
Unfortunately not, we were unable to find a workable solution to address this in time for 1.0. It is currently prioritized for 1.1.

**Comment by aparajit-pratap** [comment]
This should be fixed in 1.1. Closing.

**Comment by ParametricMonkey** [comment]
@aparajit-pratap when will v1.1 be released? Its been 3 months since 1.0 was released.

**Comment by ParametricMonkey** [comment]
@aparajit-pratap I've just downloaded the latest daily build and it is still a problem. An offset greater than 7000 and the extend circular fails - it will always be circular. Its been 5 months since this issue was first resolved. When can we expect this to be resolved?

**Comment by aparajit-pratap** [comment]
@ParametricMonkey 
The fix I'm referring to here is for the bug in polycurve.offset where the offset is inconsistent with respect to the sign of the input distance. This does not fix the issue where the resulting polycurve is not correct if the input distance is a large value. These are two separate issues. The latter is targeted to be fixed in 1.2 and is related to https://github.com/DynamoDS/Dynamo/issues/5233 and https://github.com/DynamoDS/Dynamo/issues/5681. If there is still an issue with the offset direction please reopen this one. 1.1 is around the corner.

**Comment by aparajit-pratap** [comment]
@ParametricMonkey there were actually 2 issues here. The first was a bug where the offset is inconsistent with respect to the sign of the input distance. The second was the issue where the resulting polycurve is not correct if the input distance is a large value (greater than 7000 in this case). It is the former that has been fixed in 1.1. I had mistaken this issue (in my comment on Feb 24) to be related to the first one (although you do mention that as well), so I am reopening it. The second issue is a units issue with ASM and is targeted to be fixed in 1.2 and is related to #5233 and #5681.

**Comment by monikaprabhu** [comment]
@ParametricMonkey , ASM scaling issue is fixed in 1.2.3.xxxx daily builds and is available for download.(http://dynamobuilds.com).I've tested the above case and it seems fixed.    Let us know if you still see issues.
