### ISSUE TITLE
max value of number

### ISSUE THREAD

**Issue by snilling** [DynamoDS/Dynamo#7218]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
1.1.0.2094

## Operating system
Windos 10

## What did you do? 
use large number in graph, say 6640000000. (this is a number used to create a transformation between world coordinates and local Project coordinates in millimeter.

## What did you expect to see?
6640000000

## What did you see instead?
-1949934592
It seems that Dynamo is using a Int32 for storing numbers without decimals in this release? This was not an issue in previous releases. 

If i use Code Block and type 6640000000 I get the wrong output of the node, but if I type 6640000000.0 I get get the right output.....

**Comment by ke-yu** [comment]
Has been fixed in #7203  :-), please try with latest daily build.

**Comment by snilling** [comment]
Hello
I just downloaded  what appears to be the latest daily build:

[cid:image001.jpg@01D21AFD.B17D4270]

[cid:image003.png@01D21AF5.C925E7E0]

And is still experiencing the same problems:
[cid:image006.png@01D21AFD.B1788780]

Med venleg helsing

OLA GUNNAR SKIPPERVIK
Bygg og Industri, Konstruksjoner

(+47) 55 62 37 70 | ola.gunnar.skippervik@multiconsult.no<mailto:ola.gunnar.skippervik@multiconsult.no>
www.multiconsult.no<http://www.multiconsult.no/>
[cid:image004.png@01D21AF5.C925E7E0]

**Comment by ke-yu** [comment]
hi @snilling thanks for trying. The problem in preview bubble should have been fixed, but seems watch node still has issue
![untitled](https://cloud.githubusercontent.com/assets/2600379/18984841/7177eaae-8727-11e6-978f-480d33f146fe.png)

**Comment by snilling** [comment]
I don’t understand why it is not working for me?
[cid:image001.png@01D21B08.15D9CF90]

Med venleg helsing

OLA GUNNAR SKIPPERVIK
Bygg og Industri, Konstruksjoner

(+47) 55 62 37 70 | ola.gunnar.skippervik@multiconsult.no<mailto:ola.gunnar.skippervik@multiconsult.no>
www.multiconsult.no<http://www.multiconsult.no/>
[cid:image002.png@01D21B08.15D9CF90]

**Comment by ke-yu** [comment]
@snilling it does have in watch node. Fixing it.

**Comment by ke-yu** [comment]
PR #7224 is to fix big number in watch node.

**Comment by ke-yu** [comment]
@snilling I just realize that the fix is not in the build. You have to wait for a couple of days. Sorry for that.

**Comment by ke-yu** [comment]
@snilling I'm closing this one. Please test on the latest build.
