### ISSUE TITLE
No geometry

### ISSUE THREAD

**Issue by afandianzo** [DynamoDS/Dynamo#7854]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

1.3.0.875

## Operating system

Windows 10 - 64bit

## What did you do? 

I use Dynamo Revit in my computer with no problem BUT when I use Dynamo Studio nothing shows up, I mean whatever I try to run no geometry  created I cant create even a point.

## What did you expect to see?

geometry, for example I want to build a simple box I couldn't I did the same things in Dynamo Revit and it works great but not in Dynamo studio

## What did you see instead?
Nothing

**Comment by JarodSchultz** [comment]
You are not alone in this issue. Currently working with Autodesk tech support on figuring out the problem. Already tried the laptop dual graphics card solution to no-avail... Looking at DirectX issues at this point... Once we figure it out I will post the solution...

**Comment by aparajit-pratap** [comment]
Please try installing the DirectX runtimes from here: https://www.microsoft.com/en-us/download/details.aspx?id=8109

**Comment by DanielHurtubise** [comment]
I'm in the same boat :)
Just tried the direct X version they sent me but no luck.

**Comment by afandianzo** [comment]
Thank you all,
I Also tried the DirectX but still I have the same problem. I will be waiting for your post JarodSchultz.

**Comment by JarodSchultz** [comment]
[https://github.com/DynamoDS/Dynamo/wiki/Known-Issues](url) I have tried all of the other suggestions in this link...

**Comment by aparajit-pratap** [comment]
@riteshchandawar any ideas?

**Comment by JarodSchultz** [comment]
Reached back out to Autodesk support that the issue is still not fixed, haven't heard back...

**Comment by mjkkirschner** [comment]
It's possible to try forcing software fallback by either disabling your display driver or - or installing and sdk:

https://gamedev.stackexchange.com/questions/24206/forcing-a-game-to-use-direct3d-warp

Not a great solution, but we might learn something if the software fallback works or does not.

**Comment by mjkkirschner** [comment]
also @JarodSchultz have you tried forcing dynamo to open with your integrated card instead of the high performance one?

**Comment by JarodSchultz** [comment]
I have tried enabling and disabling the graphics cards, in the Nvidia driver and at the BIOS.... Doesn't help either way... Again, if I start Revit and start Dynamo from there all is fine. It is just running Dynamo Studio by itself is when I can't see the background geometry.

**Comment by jnealb** [comment]
@JarodSchultz @mjkkirschner Is it possible for us to remote into your machine?

**Comment by JarodSchultz** [comment]
You bet... How do you want to start?

**Comment by jnealb** [comment]
What timezone are you in? What is a good day/time for you? We use TeamViewer but can use other tools as well.

**Comment by JarodSchultz** [comment]
I'm in Denver, MST timezone... I will be back in the office by 12:30pm, shoot me an email, it is my profile... Thanks!

**Comment by jnealb** [comment]
FYI @kronz @Racel @aparajit-pratap. In a first investigation with @mjkkirschner we found that the ADSK Upgrade process for Studio from 1.1 to 1.3 failed to upgrade Studio correctly to 1.3 on Windows 10 (from the icon in the tray at lower right). Follow-up support for this failure is with his ADSK contact: Pawel Romaniuk. Jarod is able to work with Studio 1.1 (gfx work) but still needs help upgrading to 1.3.

**Comment by JarodSchultz** [comment]
Thanks Neal and Mike for the help! Now the next fun part getting it go from 1.1 to 1.3 - at least we are getting closer...

**Comment by afandianzo** [comment]
For now, is there is a way to connect dynamo Revit version to project Fractal?

**Comment by afandianzo** [comment]
The Geometry problem is solved.
1.Delete Dynamo Studio
2.Re-download it
3.Use  Autodesk desktop App to update Dynamo

Now it is working

Thank you all

**Comment by JarodSchultz** [comment]
Are you sure it worked? I have done that, and Dynamo Studio is stuck on 1.1. The Update acts like it is working but when you go to help ->About it still shows 1.1. Plus when I start Revit 2018 it throws an error since it wants 1.3 of Dynamo Core...

Then if I update Dynamo Core to 1.3 which then fixes Dynamo Studio and Revit Dynamo it breaks the geometry background and I'm right back to where I was... Wonderful merry-go-around...

**Comment by awhelton** [comment]
Same problem here. I tried afandianzo's posted solution but it still does not work. 
Revit Dynamo works but Dynamo Studio (1.3.0.875) does not display geometry.
Thoughts?

**Comment by PawelRomaniuk** [comment]
@afandianzo could answer in reference to Jard question and specify your current setup?

**Comment by mjkkirschner** [comment]
@JarodSchultz was this issue resolved so that you could get both studio and dynamo revit working?

**Comment by JarodSchultz** [comment]
Yes it was, I had to get Autodesk support & Zach Kron involved to get it fixed. It was an issue on how the multiple "patches" were being installed to update Dynamo Studio and Dynamo for Revit to version 1.3
