### ISSUE TITLE
[Node]Curve.Offset working error

### ISSUE THREAD

**Issue by Alucardzh** [DynamoDS/Dynamo#9772]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version
DynamoCore 2.0.1.5055 & DynamoRevit 2.0.1.5065
DynamoCore 1.3.0.875 & DynamoStudio 1.3.0.946

## Operating system
Windows 10

## What did you do? 
When i use the node named Curve.Offset to make the rectangle expand, I find that when input number of the parameter named distance more than 7071mm, the Output of Curve.Offset will become a circle.

## What did you expect to see?
Rectangle always be a Rectangle.

## What did you see instead?
![image](https://user-images.githubusercontent.com/25925153/58920818-6b697c80-8766-11e9-8b1a-ed5840462ded.png)
![image](https://user-images.githubusercontent.com/25925153/58920823-70c6c700-8766-11e9-97a1-3df53a168904.png)

**Comment by JacobSmall** [comment]
Set the geometry working range to 'large' and this should resolve the issue.

**Comment by mjkkirschner** [comment]
please reopen if the working range suggestion does not resolve it.
